apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: my-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        version: v1.0.0
    spec:
      containers:
      - name: my-app
        image: containersol/k8s-deployment-strategies-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: v1.0.0
        livenessProbe:
          httpGet:
            path: /-/liveness
            port: 8081
        readinessProbe:
          httpGet:
            path: /-/readiness
            port: 8081
          failureThreshold: 1
          periodSeconds: 1
